CREATE TABLE Buy (
  fk_Client_id INTEGER,
  fk_Product_id INTEGER,
  fk_Ticket_qr_code VARCHAR
);
ALTER TABLE Buy ADD CONSTRAINT FK_Buy_1 FOREIGN KEY (fk_Client_id) REFERENCES Client (id) ON DELETE NO ACTION;
ALTER TABLE Buy ADD CONSTRAINT FK_Buy_2 FOREIGN KEY (fk_Product_id) REFERENCES Product (id) ON DELETE NO ACTION;
ALTER TABLE Buy ADD CONSTRAINT FK_Buy_3 FOREIGN KEY (fk_Ticket_qr_code) REFERENCES Ticket (qr_code) ON DELETE NO ACTION;