CREATE TABLE Ticket (
  qr_code VARCHAR PRIMARY KEY,
  fk_Event_id INTEGER,
  fk_Client_id INTEGER 
  );
ALTER TABLE Ticket ADD CONSTRAINT FK_Ticket_2 FOREIGN KEY (fk_Event_id) REFERENCES Event (id) ON DELETE RESTRICT;
